apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "breakfast-club.fullname" . }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "breakfast-club.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "breakfast-club.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: {{ include "breakfast-club.fullname" . }}-config
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
