apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migration
  namespace: prod
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: laravel-migration
        namespace: prod
    spec:
      restartPolicy: Never
      containers:
      - name: php-fpm
        image: ghcr.io/ajn123/breakfast-club-php-fpm:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            cd /var/www/laravel/current && \
            php artisan migrate --force && \
            php artisan db:seed --force
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password