version: '3.8'

services:
  api:
    build:
      context: ../../api
      dockerfile: ../docker/dev/api/Dockerfile
    container_name: dev-api
    volumes:
      - ../../api:/var/www
      - api-vendor:/var/www/vendor
      - /var/www/node_modules
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VITE_POLLING=true
    ports:
      - "5173:5173" # Vite dev server port
    depends_on:
      - postgres
    networks:
      - dev-network

  nginx:
    image: nginx:alpine
    container_name: dev-nginx
    ports:
      - "8080:80"
    volumes:
      - ../../api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - dev-network

  postgres:
    image: postgres:15-alpine
    container_name: dev-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
  api-vendor:
