apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: prod
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      securityContext:
        runAsUser: 0        # Run as root
        fsGroup: 0          # Access to filesystem
      containers:
      - name: fluentd
        image: grafana/fluent-bit-plugin-loki:latest
        securityContext:
          privileged: true  # Needed for log access
        env:
          - name: LOKI_URL
            value: http://loki:3100
          - name: LOKI_USERNAME
            value: ""
          - name: LOKI_PASSWORD
            value: ""
          - name: FLUENT_UID
            value: "0"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluent-bit/etc
        - name: pos-files
          mountPath: /fluentd/pos
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: pos-files
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: prod
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/containers/*.log
        Parser      docker
        Tag         kube.*
        Mem_Buf_Limit  5MB
        Skip_Long_Lines On

    [INPUT]
        Name        tail
        Path        /var/log/mysql/mysql*.log
        Parser      mysql
        Tag         mysql.*

    [FILTER]
        Name        kubernetes
        Match       kube.*
        Merge_Log   On
        Keep_Log    Off
        K8S-Logging.Parser    On
        K8S-Logging.Exclude   Off

    [OUTPUT]
        Name        loki
        Match       *
        Host        loki
        Port        3100
        Labels      job=fluentbit, app=$kubernetes['labels']['app'], container=$kubernetes['container_name'], pod=$kubernetes['pod_name'], namespace=$kubernetes['namespace']
        Remove_Keys kubernetes,stream,time,tag

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        mysql
        Format      regex
        Regex       ^(?<time>[^ ]* [^ ]*) [^]]*] (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S 