apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-api
  namespace: laravel-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-api
  template:
    metadata:
      labels:
        app: laravel-api
    spec:
      containers:
      - name: api
        image: your-registry/laravel-api:dev
        envFrom:
        - configMapRef:
            name: laravel-config
        - secretRef:
            name: laravel-secret 