apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
  type: ClusterIP