apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: prod
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.14.0
        ports:
        - containerPort: 9104
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-secret
              key: data-source-name
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: prod
type: Opaque
stringData:
  data-source-name: "root:your-password@(mysql.prod.svc.cluster.local:3306)/"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: prod
  labels:
    app: mysql-exporter
spec:
  ports:
  - port: 9104
    name: metrics
  selector:
    app: mysql-exporter 
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: database-monitor
  namespace: prod
  labels:
    release: prometheus  # Add this label
spec:
  selector:
    matchLabels:
      monitoring: "true"
  namespaceSelector:
    matchNames:
      - prod
  endpoints:
  - port: metrics
    interval: 30s