apiVersion: v1
kind: ConfigMap
metadata:
  name: breakfast-club-config
  namespace: prod
data:
  db-host: "prod-db-host"
  app-url: "https://breakfast-club.yourdomain.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: breakfast-club-secrets
  namespace: prod
type: Opaque
data:
  app-key: "YmFzZTY0LWVuY29kZWQtYXBwLWtleQ=="
  db-password: "YmFzZTY0LWVuY29kZWQtZGItcGFzc3dvcmQ=" 