ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: breakfast-club.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: breakfast-club-tls
      hosts:
        - breakfast-club.yourdomain.com 