apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: prod
data:
  APP_NAME: "Laravel"
  APP_ENV: "development"
  APP_KEY: "base64:VvzF7Q8c7B2f9ky7WPuLeL7YXj/qD8XiUmANvcXwoXE="
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "https://touchgrassdc.com"
  VITE_APP_URL: "https://touchgrassdc.com"


  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"

  PHP_CLI_SERVER_WORKERS: "4"

  BCRYPT_ROUNDS: "12"

  DB_QUERY_LOG: "true"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"
  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  CACHE_STORE: "database"
  CACHE_PREFIX: ""
  MEMCACHED_HOST: "127.0.0.1"
  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "redis"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: "null"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  VITE_APP_NAME: "${APP_NAME}"
  FORWARD_DB_PORT: ""
  DATA_PATH_HOST: "~/.sail/data"
  DOCKER_HOST_IP: "172.17.0.1"
  APP_CODE_PATH_HOST: "./"
  APP_CODE_PATH_CONTAINER: "/var/www/laravel/current"
  APP_CODE_CONTAINER_FLAG: "cached"
  NGINX_HOST_HTTP_PORT: "80"
  NGINX_HOST_HTTPS_PORT: "443"
  NGINX_HOST_LOG_PATH: "./docker/logs/nginx/"
  NGINX_SITES_PATH: "./docker/nginx/sites/"
  NGINX_PHP_UPSTREAM_CONTAINER: "php-fpm"
  NGINX_PHP_UPSTREAM_PORT: "9000"
  NGINX_SSL_PATH: "./docker/nginx/ssl/"
  SCOUT_DRIVER: "meilisearch"
  MEILISEARCH_HOST: "meilisearch:7700"
  MEILISEARCH_KEY: "masterKey"
  OCTANE_SERVER: "frankenphp"
  OCTANE_HTTPS: "true"
