apiVersion: autoscaling/v1
kind: HorizontalPodAutoscalar
metadata:
  name: php-app-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
