apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app2
spec:
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      initContainers:
      - name: copy-app
        image: registry.digitalocean.com/api-registry-unified/api-php-fpm:latest
        command: ['/bin/sh', '-c', 'cp -r /var/www/laravel/current/. /shared/ && chmod -R 777 /shared']
        volumeMounts:
        - name: laravel-storage
          mountPath: /shared

      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: laravel-storage
          mountPath: /var/www/laravel/current
        - name: nginx-ssl
          mountPath: /etc/nginx/ssl
      
      - name: php-fpm
        image: registry.digitalocean.com/api-registry-unified/api-php-fpm:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/laravel/current
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_DATABASE
          value: "myapp"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: laravel-storage
        emptyDir: {}
      - name: nginx-ssl
        emptyDir: {}


