apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      initContainers:
      - name: copy-app
        image: ghcr.io/ajn123/breakfast-club-php-fpm:latest
        command: ['/bin/sh', '-c', 'cp -r /var/www/laravel/current/. /shared/ && chmod -R 777 /shared']
        volumeMounts:
        - name: laravel-storage
          mountPath: /shared

      containers:
      - name: nginx
        image:  ghcr.io/ajn123/breakfast-club-nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/laravel/current
      
      - name: php-fpm
        image: ghcr.io/ajn123/breakfast-club-php-fpm:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/laravel/current
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_DATABASE
          value: "myapp"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
      volumes:
      - name: laravel-storage
        emptyDir: {}


