apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: prod
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--appendonly yes"]
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
