apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: prod
spec:
  selector:
    app: php-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443 
    targetPort: 443
  type: ClusterIP 

    