apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-app2  # Match your deployment labels
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port 