services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      DB_HOST: pgsql # Use the service name as the host
      DB_PORT: 5432
      DB_DATABASE: your_database_name
      DB_USERNAME: your_username
      DB_PASSWORD: your_password

  pgsql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
