name: Laravel CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: laravel_test_db
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_pgsql
    
    - name: Copy .env
      run: |
        cd api
        cp .env.example .env
        sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=pgsql/' .env
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=localhost/' .env
        sed -i 's/DB_PORT=3306/DB_PORT=5432/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel_test_db/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=developer/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=secret/' .env
        
    - name: Install Dependencies
      run: |
        cd api
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Generate key
      run: |
        cd api
        php artisan key:generate
    
    - name: Directory Permissions
      run: |
        cd api
        chmod -R 777 storage bootstrap/cache
    
    - name: Run Migrations
      run: |
        cd api
        php artisan migrate --force
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: laravel_test_db
        DB_USERNAME: developer
        DB_PASSWORD: secret
    
    - name: Run Tests
      run: |
        cd api
        php artisan test
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: laravel_test_db
        DB_USERNAME: developer
        DB_PASSWORD: secret

  deploy-dev:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./docker/dev/api/Dockerfile
        push: true
        tags: your-registry/laravel-api:dev 